In [3]:
import numpy as np

In [5]:
print(np.__version__)

1.20.3


In [7]:
L = list(range(100))

In [8]:
print (L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [9]:
type(L[10])

int

In [11]:
L2 = [str(i) for i in L]
print(L2)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99']


In [12]:
L3 = [True, "3", 4.5, 8]
print([type(item) for item in L3])

[<class 'bool'>, <class 'str'>, <class 'float'>, <class 'int'>]


# Creating arrays from Python lists

In [14]:
L4 = np.array(L2, dtype = int)
print(L4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [24]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# creating arrays from scratch

In [15]:
np.ones((4,6), dtype = int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [16]:
np.arange(0, 1000, 1.5)

array([  0. ,   1.5,   3. ,   4.5,   6. ,   7.5,   9. ,  10.5,  12. ,
        13.5,  15. ,  16.5,  18. ,  19.5,  21. ,  22.5,  24. ,  25.5,
        27. ,  28.5,  30. ,  31.5,  33. ,  34.5,  36. ,  37.5,  39. ,
        40.5,  42. ,  43.5,  45. ,  46.5,  48. ,  49.5,  51. ,  52.5,
        54. ,  55.5,  57. ,  58.5,  60. ,  61.5,  63. ,  64.5,  66. ,
        67.5,  69. ,  70.5,  72. ,  73.5,  75. ,  76.5,  78. ,  79.5,
        81. ,  82.5,  84. ,  85.5,  87. ,  88.5,  90. ,  91.5,  93. ,
        94.5,  96. ,  97.5,  99. , 100.5, 102. , 103.5, 105. , 106.5,
       108. , 109.5, 111. , 112.5, 114. , 115.5, 117. , 118.5, 120. ,
       121.5, 123. , 124.5, 126. , 127.5, 129. , 130.5, 132. , 133.5,
       135. , 136.5, 138. , 139.5, 141. , 142.5, 144. , 145.5, 147. ,
       148.5, 150. , 151.5, 153. , 154.5, 156. , 157.5, 159. , 160.5,
       162. , 163.5, 165. , 166.5, 168. , 169.5, 171. , 172.5, 174. ,
       175.5, 177. , 178.5, 180. , 181.5, 183. , 184.5, 186. , 187.5,
       189. , 190.5,

In [17]:
np.linspace(0, 10, 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [20]:
np.random.normal(25, 12, (5,6))

array([[ 4.13909276, 25.98822165, 53.3169962 , 36.01409215, 37.849804  ,
        23.20313291],
       [24.09929333, 25.2434696 , 22.2931398 , 20.54154999, 21.01445453,
        23.54503537],
       [18.04107612, 37.48177521, 19.36477612, 13.92817057, 21.64521988,
        31.45417425],
       [24.76652833, 10.97649192, 27.87137802, 28.64309701, 44.07243339,
        21.86047154],
       [27.87636455, 27.00511314,  7.63006377, 15.35649691, 27.2026498 ,
        12.5148136 ]])

In [21]:
np.random.randint(0,100,(3,3))

array([[56, 70, 38],
       [49, 92, 49],
       [89, 68, 78]])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Numpy Array Attributes
We’ll use
NumPy’s random number generator, which we will seed with a set value in order to
ensure that the same random arrays are generated each time this code is run:

In [27]:
np.random.seed(0) #seed for reproducibility
x1 = np.random.randint(10, size=6) #one-dimensional array
x2 = np.random.randint(10, size = (3, 4)) #2D array
x3 = np.random.randint(10, size = (3, 4, 5)) #3D array

In [28]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)


x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [29]:
print("dtype: ", x3.dtype)

dtype:  int32


In [30]:
print("Item Size: ", x3.itemsize, "bytes") #lists the size of each array element
print("nbytes: ", x3.nbytes, "bytes") #nbytes lists the total size of the array

Item Size:  4 bytes
nbytes:  240 bytes


In a multidimensional array, you access items using a comma-separated tuple of
indices:

In [31]:
x2[0,0]

3

You can also modify values using any of the above index notation:


In [32]:
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means,
for example, that if you attempt to insert a floating-point value to an integer array, the
value will be silently truncated. Don’t be caught unaware by this behavior!

# Array Slicing: Accessing Subarrays

In [33]:
# One-dimensionsal subarrays
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
x[5]

5

In [36]:
x[:5]#the first five elements

array([0, 1, 2, 3, 4])

In [35]:
x[5:]#the elements after index 5

array([5, 6, 7, 8, 9])

In [37]:
x[4:7]#middle subbarray

array([4, 5, 6])

In [38]:
x[::2] #every other element

array([0, 2, 4, 6, 8])

In [39]:
x[1::2] #every other element, starting at index 1

array([1, 3, 5, 7, 9])

A potentially confusing case is when the step value is negative. In this case, the
defaults for start and stop are swapped. This becomes a convenient way to reverse
an array:

In [40]:
x[::-1]#all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [41]:
x[5::-2] #reversed every other from index 5

array([5, 3, 1])

In [42]:
#Multidimensional subarrays
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [43]:
x2[:2, :3] #two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [44]:
x2[:3, ::2] #all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

subarray dimensions can even be reversed together:

In [45]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [46]:
#Acessing array rows and columns
#You can do this by combining indexing and slicing,using an empty slice marked by a single colon (:):
print(x2[:, 0]) #first column of x2

[12  7  1]


In [47]:
print(x2[0, :]) #first row of x2

[12  5  2  4]


In [48]:
print(x2[0]) # equivalent to x2[0, :] but more compact

[12  5  2  4]


Subarrays as no-copy views

In [49]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [51]:
x2_sub = x2[:2, :2] #extracting a 2X2 subarray
print(x2_sub)

[[12  5]
 [ 7  6]]


#if we modify this subarray, we’ll see that the original array is changed! Observe:

In [52]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [53]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

In [54]:
#Creating copies of arrays
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [ ]:
#If we now modify this subarray, the original array is not touched
x2_sub_copy[0]